### ISSUE TITLE
Deprecated syntax

### ISSUE THREAD

**Issue by spwebini** [dotpay/magento2-payment#12]
When going from "My cart" to checkout it shows :

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/dotpay/php-sdk/src/Locale/Adapter/AbstractAdapter.php on line 207

**Comment by wpawel** [comment]
it has already been corrected on August 29: [Update AbstractAdapter.php](https://github.com/dotpay/PHP-SDK/commit/057259a2bb47f65d8eb5b205601482e36f1f95f9#diff-a6f31c0086d0fefcd0b009d9d06818ffb3c7a0189df6291e2adacedf3d147121)

**Comment by spwebini** [comment]
Have version  "dotpay/magento2-payment": "^1.0.16" - issue still exist

**Comment by spwebini** [comment]
"dotpay/php-sdk": "^1.0.17",
