### ISSUE TITLE
You can go to dotpay proceed site even without accepting dotpay regulations at checkout

### ISSUE THREAD

**Issue by spwebini** [dotpay/magento2-payment#13]
As in title. You can go to dotpay proceed site even without accepting dotpay regulations at checkout.

Magento 2.4.1

**Comment by wpawel** [comment]
please check versions [v1.0.18](https://github.com/dotpay/magento2-payment/releases/tag/1.0.18)

**Comment by spwebini** [comment]
Still not working - can go to payment without selecting "agreements".
