### ISSUE TITLE
Wystąpił błąd z API Dotpay. Szczegóły: Kwota minimalna

### ISSUE THREAD

**Issue by rskonieczka** [dotpay/magento2-payment#3]
Po ustawieniu reguły cenowej koszyka z kuponem rabatowym, dającym rabat 100%. pojawia się następujący błąd. Opcja "Zamówienie z zerową podsumą" jest włączona.

```
1 exception(s):
Exception #0 (Dotpay\Exception\Resource\ApiException): Dotpay\Exception\Resource\ApiException: Wystąpił błąd z API Dotpay. Szczegóły: Kwota minimalna: 0.0100, kwota 0
```

**Comment by wpawel** [comment]
Kwota minimalna oraz maksymalna transakcji ustalana jest na danym koncie w Dotpay.
Nie ma możliwości zaksięgowania po stronie Dotpay transakcji na kwotę 0 zł tak samo zresztą jak w polskich bankach.
Jeśli nie ma płatności to po co w ogóle korzystać w takiej sytuacji z modułu płatności ?
