### ISSUE TITLE
Fatal error PHP 7.0

### ISSUE THREAD

**Issue by stalica** [dotpay/magento2-payment#5]
Magento 2.2.6

Fatal error:  Interface 'Magento\Framework\App\CsrfAwareActionInterface' not found in /public_html/vendor/dotpay/magento2-payment/Controller/Payment/Diagnostics.php on line 34

Niezgodność z PHP 7.0
    public function createCsrfValidationException(RequestInterface $request): ?InvalidRequestException

**Comment by MrBloodyJohn** [comment]
Problem leży w tym, że próbują Państwo zainstalować niekompatybilny moduł do Magento 2.2.6. Ostatnia wersja, tj. 1.0.13, wymagana do poprawnego działania Magento w wersji 2.3 i PHP w wersji minimum 7.1, co zostało uwzględnione w pliku konfiguracyjnym composer.json. Jeśli zamierzają Państwo korzystać ze wskazanej wersji 2.2.6, należy zainstalować moduł płatności, który dopuszcza taką konfigurację w swojej konfiguracji.

**Comment by stalica** [comment]
Moduł obecnie ma zbyt restrykcyjne wymagania kompatybilności, co zawęża możliwość jej zastosowania, nie tędy droga. Nie próbowałem go zainstalować, a poszła automatyczna aktualizacja przez composera, a nie powinna z uwagi na brak kompatybilności!

Z takim podejściem to będziecie sobie sami używali tego modułu, a klienta przenoszę do waszej konkurencji która potrafi pisać moduły dla Magento 2.
